### ISSUE TITLE
Asterisk 12 make problems

### ISSUE THREAD

**Issue by jersonjunior** [jstasiak/asterisk-chan-dongle#1]
make
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT app.o -MF .app.o.d -MP  -o app.o -c app.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT at_command.o -MF .at_command.o.d -MP  -o at_command.o -c at_command.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT at_parse.o -MF .at_parse.o.d -MP  -o at_parse.o -c at_parse.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT at_queue.o -MF .at_queue.o.d -MP  -o at_queue.o -c at_queue.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT at_read.o -MF .at_read.o.d -MP  -o at_read.o -c at_read.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT at_response.o -MF .at_response.o.d -MP  -o at_response.o -c at_response.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include -DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT chan_dongle.o -MF .chan_dongle.o.d -MP  -o chan_dongle.o -c chan_dongle.c
chan_dongle.c: In function ‘public_state_init’:
chan_dongle.c:1668:45: error: too few arguments to function ‘ast_format_cap_alloc’
           if (!(channel_tech.capabilities = ast_format_cap_alloc())) {
                                             ^
In file included from /usr/include/asterisk/format_pref.h:28:0,
                 from /usr/include/asterisk/frame.h:34,
                 from cpvt.h:9,
                 from chan_dongle.h:18,
                 from chan_dongle.c:60:
/usr/include/asterisk/format_cap.h:52:24: note: declared here
 struct ast_format_cap *ast_format_cap_alloc(enum ast_format_cap_flags flags);
                        ^
Makefile:65: recipe for target 'chan_dongle.o' failed
make: *** [chan_dongle.o] Error 1

**Comment by jstasiak** [comment]
I'll close this issue as part of closing down the issue section (it's not my intention to imply that this project is supported in any way).
