### ISSUE TITLE
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'

### ISSUE THREAD

**Issue by vinnitu** [jstasiak/asterisk-chan-dongle#3]
# aclocal --version
aclocal (GNU automake) 1.14.1

# automake --version
automake (GNU automake) 1.14.1

# autoconf --version
autoconf (GNU Autoconf) 2.69

what is wrong?

Ubuntu 14.04 x64

**Comment by jstasiak** [comment]
I'll close this issue as part of closing down the issue section (it's not my intention to imply that this project is supported in any way).
