### ISSUE TITLE
Problems connecting

### ISSUE THREAD

**Issue by junalmeida** [jstasiak/asterisk-chan-dongle#4]
I could successfuly compile and load chan_dongle for asterisk11 in a Elastix system. 
But debugging, I cannot connect do my modem. Can you help?

```
    -- [dongle0] Trying to connect on /dev/ttyUSB_utps_modem...
    -- [dongle0] Dongle has connected, initializing...
[2015-01-14 23:02:30] ERROR[3616]: chan_dongle.c:436 do_monitor_phone: [dongle0] timedout while waiting 'OK' in response to 'AT'
    -- [dongle0] Error initializing Dongle
    -- [dongle0] Dongle has disconnected
```

I can issue AT coomand on minicom on the same device, and I got OK messages.

**Comment by cywin025** [comment]
Really sorry，I have no experience on dongle.I work on Cable modem, eMTA.
The asterisk source code is for my git practice. ‍




------------------ 原始邮件 ------------------
发件人: "Marcos Junior";<notifications@github.com>;
发送时间: 2015年1月15日(星期四) 上午9:03
收件人: "jstasiak/asterisk-chan-dongle"<asterisk-chan-dongle@noreply.github.com>; 

主题: [asterisk-chan-dongle] Problems connecting (#4)




I could successfuly compile and load chan_dongle for asterisk11 in a Elastix system. 
 But debugging, I cannot connect do my modem. Can you help?
     -- [dongle0] Trying to connect on /dev/ttyUSB_utps_modem...     -- [dongle0] Dongle has connected, initializing... [2015-01-14 23:02:30] ERROR[3616]: chan_dongle.c:436 do_monitor_phone: [dongle0] timedout while waiting 'OK' in response to 'AT'     -- [dongle0] Error initializing Dongle     -- [dongle0] Dongle has disconnected  
I can issue AT coomand on minicom on the same device, and I got OK messages.

**Comment by jon-uk** [comment]
Have you checked permission on /dev/ttyUS*? Try chmod 777.

goci

**Comment by jstasiak** [comment]
I'll close this issue as part of closing down the issue section (it's not my intention to imply that this project is supported in any way). I recommend raising this with the author of the project.
