### ISSUE TITLE
Cannot find some dongles

### ISSUE THREAD

**Issue by liberatorcnx** [jstasiak/asterisk-chan-dongle#6]
I have 2 sites each with a 49 port usb hub and each hub having 40 dongles.  The hub appears in lsusb as 7 usb hobs each with 7 ports.  Here is the response to lsusb ;
~# lsusb
Bus 002 Device 017: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 117: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 016: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 115: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 015: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 021: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 114: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 009: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 031: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 029: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 025: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 028: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 024: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 027: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 032: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 008: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 044: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 049: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 043: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 042: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 048: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 050: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 041: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 007: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 057: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 056: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 052: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 055: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 051: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 054: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 058: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 006: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 060: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 116: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 118: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 020: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 097: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 096: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 030: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 005: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 018: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 110: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 098: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 095: ID 12d1:1436 Huawei Technologies Co., Ltd. E173 3G Modem (modem-mode)
Bus 002 Device 010: ID 12d1:1446 Huawei Technologies Co., Ltd. E1552/E1800/E173 (HSPA modem)
Bus 002 Device 004: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 003: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 002: ID 1a40:0201 Terminus Technology Inc. FE 2.1 7-port Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

Each dongle is entered in to dongle.conf with only the imei number.  Problem is on startup or core reload asterisk only recognises about 50% of the dongles.  If I do a usbreset for any of the hubs astersik still only sees around half of the dongles.

Here is a response to 'dongle list devices':

*CLI> dongle show devices
ID           Group State      RSSI Mode Submode Provider Name  Model      Firmware          IMEI             IMSI             Number
dongle1      0     Free       23   0    0       Telenor@       E173       11.126.16.04.617  868860002401352  414061106110484  Unknown
dongle2      0     Not connec 0    0    0       NONE                                                                          Unknown
dongle3      0     Not connec 0    0    0       NONE                                                                          Unknown
dongle4      0     Not connec 0    0    0       NONE                                                                          Unknown
dongle5      0     Not connec 0    0    0       NONE                                                                          Unknown
dongle6      0     Not connec 0    0    0       NONE                                                                          Unknown
dongle7      0     Free       25   0    0       Telenor@       E173       11.126.16.04.617  868860002399739  414061106110476  Unknown
dongle8      0     Free       22   0    0                      E173       11.126.16.04.617  868860002397782  414061106110489  Unknown
dongle9      0     Free       22   0    0       Telenor@       E173       11.126.16.04.617  868860002401022  414061106110490  Unknown
dongle10     0     Free       20   0    0       Telenor@       E173       11.126.16.04.617  868860002399101  414061106110491  Unknown
dongle11     0     Free       21   0    0                      E173       11.126.16.04.617  868860002403762  414061106112403  Unknown
dongle12     0     Free       21   0    0       Telenor@       E173       11.126.16.04.617  868860002403051  414061106110488  Unknown
dongle13     0     Free       19   0    0                      E173       11.126.16.04.617  868860002361093  414061106112395  Unknown
dongle14     0     Free       23   0    0                      E173       11.126.16.04.617  868860002401576  414061106112405  Unknown
dongle15     0     Free       15   0    0       Telenor@       E173       11.126.16.04.617  868860002402673  414061106464824  Unknown
dongle16     0     Free       19   0    0       Telenor@       E173       11.126.16.04.617  868860002361085  414061106111024  Unknown
dongle17     0     Not connec 0    0    0       NONE                                                                          Unknown
dongle18     0     Free       20   0    0       Telenor@       E173       11.126.16.04.617  868860002401683  414061106111015  Unknown
dongle19     0     Free       19   0    0       Telenor@       E173       11.126.16.04.617  868860002398319  414061108997851  Unknown
dongle20     0     Free       19   0    0                      E173       11.126.16.04.617  868860002399366  414061108997852  Unknown
dongle21     0     Free       22   0    0       Telenor@       E173       11.126.16.04.617  868860002362448  414061108997838  Unknown
dongle22     0     Free       21   0    0       Telenor@       E173       11.126.16.04.617  868860002359477  414061108997849  Unknown
dongle23     0     Free       20   0    0       Telenor@       E173       11.126.16.04.617  868860002397576  414061108997835  Unknown
dongle24     0     Not connec 0    0    0       NONE                                                                          Unknown
dongle25     0     Not connec 0    0    0       NONE                                                                          Unknown
dongle26     0     Free       17   0    0       Telenor@       E173       11.126.16.04.617  868860002398608  414061108997842  Unknown
dongle27     0     Free       20   0    0       Telenor@       E173       11.126.16.04.617  868860002398368  414061108997845  Unknown
dongle28     0     Free       20   0    0       Telenor@       E173       11.126.16.04.617  868860002398236  414061108997843  Unknown
dongle29     0     Free       22   0    0       Telenor@       E173       11.126.16.04.617  868860002362489  414061108997841  Unknown
dongle30     0     Free       21   0    0       Telenor@       E173       11.126.16.04.617  868860002398616  414061108997848  Unknown
dongle31     0     Not connec 0    0    0       NONE                                                                          Unknown
dongle32     0     Free       21   0    0       Telenor@       E173       11.126.16.04.617  868860002399879  414061108997833  Unknown
dongle33     0     Not connec 0    0    0       NONE                                                                          Unknown
dongle34     0     Free       0    0    0       Telenor@       E173       11.126.16.04.617  868860002358735  414061108997839  Unknown
dongle35     0     GSM not re 25   0    0       NONE           E173       11.126.16.04.617  868860002398533  414061108997834  Unknown
dongle36     0     Free       22   0    0       Telenor@       E173       11.126.16.04.617  868860002398301  414061108997837  Unknown
dongle37     0     Free       25   0    0       Telenor@       E173       11.126.16.04.617  868860002399747  414061108997846  Unknown
dongle38     0     Free       23   0    0       Telenor@       E173       11.126.16.04.617  868860002398921  414061108997850  Unknown
dongle39     0     Free       24   0    0                      E173       11.126.16.04.617  868860002398723  414061108997872  Unknown
dongle40     0     Not connec 0    0    0       NONE 

This was after 3 reboots.  Each reboot seems to result in more dongles connected ???

I also have a constant message in verbose mode like this : 

[May  2 19:40:32] ERROR[3580]: at_response.c:119 at_response_ok: [dongle9] Received unexpected 'OK'

So how is 'OK' enexpected?  I get this for many dongles...

Maybe nobody tried with so many dongles before and I need to change some things in the source to make this work?

**Comment by jstasiak** [comment]
I'm sorry, I have no knowledge or time capacity to help here.

I'll close this issue as part of closing down the issue section (it's not my intention to imply that this project is supported in any way). I recommend raising this with the author of the project.
